### ISSUE TITLE
build problems

### ISSUE THREAD

**Issue by SIRprise** [ola-ct/pwned#2]
Background:
I wanted to make a RPi2 server to test my passwords... (Raspbian Buster, GCC7.1) It isn't important to me, if it needs some some ms oder a second to check.

Problems & Solutions:
I had to install some additional boost librarys...
prepend NO_POPCNT=1 did not work, I guess it must be -DNO_POPCNT=1  - I fixed it by removing the condition in the CMAKE lists file.
Afterwards make didn't know the "-mno-popcnt" command -> I deleted it and it compiled via make (without j 5) in ~10 minutes. The j 5 option needed that much RAM and CPU that the whole system didn't respond. Without it needed ~700MB RAM and compiled.

**Comment by ola-ct** [comment]
Thanks for your report!

What happened when compiling with POPCNT enabled? Any error messages? Code not working?

**Comment by ola-ct** [comment]
Investigating issue on freshly installed Raspi 4 w/ Debian Buster ...

**Comment by ola-ct** [comment]
Regarding `-j 5` see 00f8c902f60fe675ec558d3c9962e32025fd265f
